name: Build/Publish Image

on: workflow_dispatch

env:
  BUILDX_CACHE_DIR: /tmp/buildx
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Version Info
      id: versions
      run: |
        elixir_version="$(cat VERSION | grep elixir | cut -d ' ' -f2)"
        echo "::set-output name=elixir_version::${elixir_version}"

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker Layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/buildx
        key: buildx-elixir${{ steps.versions.outputs.elixir_version }}
        restore-keys: |
          buildx-elixir${{ steps.versions.outputs.elixir_version }}
          buildx-elixir

    - name: Build Image
      run: make build

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Image
      run: make release
